### ISSUE TITLE
code doesn't retain structure

### ISSUE THREAD

**Issue by royzinn** [JuanitoFatas/html-pipeline-rouge_filter#4]
Hi,
I am using this gem and when I render the result, it looks broken:
![screenshot 2015-10-30 22 00 09](https://cloud.githubusercontent.com/assets/519388/10856777/7d057572-7f52-11e5-8f9c-243e76bdf226.png)

the code i'm using to render this is:

``` ruby
def markdownify(content)
    pipeline_context = { gfm: true, asset_root: "public/images" }
    pipeline = HTML::Pipeline.new [
      HTML::Pipeline::MarkdownFilter,
      HTML::Pipeline::SanitizationFilter,
      HTML::Pipeline::RougeFilter,
      HTML::Pipeline::MentionFilter,
      HTML::Pipeline::EmojiFilter,
    ], pipeline_context
    pipeline.call(content)[:output].to_s.html_safe
  end
```

and I call it on:

``` ruby
.media-body
    .media-heading
      %small.pull-right.text-muted= time_ago_in_words comment.created_at
      %h5= comment.user.username
    %p= markdownify comment.comment
```

any idea what might be the issue?
BTW - inspecting the styles in DevTools doesn't show any additional paddings, spaces, margins or whatever added
Thanks

**Comment by JuanitoFatas** [comment]
I have tried to reproduce your issue (94a1bd9), but cannot reproduce it :sweat_smile: . Could you try a Pull Request like 94a1bd9 that reproduce your issue :bow: ? Thanks!

**Comment by royzinn** [comment]
Hi @JuanitoFatas - not sure I understand what exactly do you want me to put in the pull request...

The strangest part is that when I inspect element, right click on the `<code>` tag and try `Edit as HTML`, there are many spaces between the `<span>` tags (shouldn't the browser ignore them?) and if I remove them, it looks good. 
I have no idea what causes the rendering to look like that, I inspected the returned code and it looks like regular string with some line breaks for the code

**Comment by royzinn** [comment]
OK - after digging in some more, it looks like the issue is coming from css, in specifics, the white-space attribute. when I change the this attribute, it looks better, still need to figure out how to maintain the spaces within the code
