### ISSUE TITLE
Replace new line "<br>" in the html document 

### ISSUE THREAD

**Issue by allenwq** [JuanitoFatas/html-pipeline-rouge_filter#6]
The <br>s inside <pre></pre> should be handled and replaced with \n in the html document.

Here's a example which does not render correctly:
<pre lang="python"><code>def square(x):<br>&nbsp; &nbsp; return x \* x</code></pre>

**Comment by lowjoel** [comment]
This is the case when using HTML editors, even within a pre/code block, the editors will insert <br> instead of just appending a newline. Rouge won't accept that as part of syntax, and Nokogiri doesn't convert <br> to newlines either...

**Comment by allenwq** [comment]
@JuanitoFatas Any comments ?

**Comment by JuanitoFatas** [comment]
I agree with @lowjoel, and this repo is only focus on adding Rouge support to html-pipeline, I think you can try open an issue to [html-pipeline](https://github.com/jch/html-pipeline) instead. : )

**Comment by allenwq** [comment]
@JuanitoFatas I don't think this issue is belongs to html-pipeline, there is nothing wrong on both side (html-pipeline and rouge). 

Also you might get @lowjoel wrongly ?

**Comment by JuanitoFatas** [comment]
What can we do in html-pipeline-rouge_filter :blush: ?

**Comment by allenwq** [comment]
@JuanitoFatas Thanks for reopening the issue :)

I think we should replace the <br> inside text before passing to rouge: https://github.com/JuanitoFatas/html-pipeline-rouge_filter/blob/master/lib/html/pipeline/rouge_filter.rb#L17

**Comment by JuanitoFatas** [comment]
> I think we should replace the 
> inside text before passing to rouge: https://github.com/JuanitoFatas/html-pipeline-rouge_filter/blob/master/lib/html/pipeline/rouge_filter.rb#L17

How about make it an option, by default won't replace. So that people still use it like before, but anyone with special needs can pass this option. What do you think? :)

**Comment by allenwq** [comment]
Yep, that looks good :+1:  I will open a PR regarding this.

**Comment by JuanitoFatas** [comment]
> Yep, that looks good  I will open a PR regarding this.

Thank you! :bow:
